<?php
// $Id$

/**
 * @param $fields
 *   Array containing detail fields.
 * @return string
 *   String containing comma separated keywords.
 */
function sru_client_taxonomy_terms($fields, $xml_module) {
  if ($field = variable_get('sru_client_taxonomy_field_'. $xml_module, '')) {
    if (isset($fields[$field])) {
      $terms = explode ('/', $fields[$field]); // We expect "term1 / term2"...
      $tags = array();
      foreach ($terms as $tag) {
        $tag = str_replace('"', '""', $tag); // Escape quotes
        $tags[] = '"'. $tag .'"'; // Quote
      }
      // See drupal_explode_tags.
      return implode(',', $tags); 
    }
  }
}

/**
 * Remove keywords field from fields array.
 *
 * @param $fields
 *   Array containing detail fields.
 * @return array
 *   Array containing detail fields.
 */
function sru_client_taxonomy_remove_taxonomy($fields, $xml_module) {
  if ($field = variable_get('sru_client_taxonomy_field_'. $xml_module, '')) {
    if (isset($fields[$field])) {
      unset($fields[$field]);
    }
  }
  return $fields;
}

/**
 * Implementation of hook_menu().
 */
function sru_client_taxonomy_menu() {
  $items = array();
  $items['admin/settings/sru/taxonomy'] = array(
    'title' => 'Asset taxonomy',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sru_client_taxonomy_admin_settings'),
    'access arguments' => array('administer SRU'),
    'file' => 'sru_client_taxonomy.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}


/**
 * Implementation of hook_nodeapi().
 */
function sru_client_taxonomy_nodeapi(&$node, $op, $teaser, $page) {
  if (!(module_exists('taxonomy'))) {
    return;
  }
  if (!($node->type == 'sru_client_asset')) {
    return;
  }
  $vid = variable_get('sru_client_taxonomy_vocabulary', '');
  $vocabulary = taxonomy_vocabulary_load($vid);
  if (empty($vocabulary) || !($vocabulary->tags)) {
    return;
  }

  switch ($op) {
    // Assign asset terms when adding or updating an asset.
    case 'presave':
      if (isset($node->sru_client_terms)) {
        $node->taxonomy['tags'] = array($vid => $node->sru_client_terms); // Overwrite.
      }
      break;
  }
  return;
}


